### ISSUE TITLE
null object 리턴의 의미

### ISSUE THREAD

**Issue by ledgku** [suji-labs/qs-java#1]
아래와 같이 `plainObjects` 옵션을 주게 되면 null object를 리턴한다.

```node
> const qs = require('qs');

> qs.parse('foo[bar]=baz');
{ foo: { bar: 'baz' } }

> qs.parse('a[hasOwnProperty]=b', { plainObjects: true });
[Object: null prototype] { a: [Object: null prototype] { hasOwnProperty: 'b' } }
```

null object는 protytpe이 null인 객체를 의미한다.

* null object 생성
![image](https://user-images.githubusercontent.com/12126093/66712165-95494480-edd3-11e9-9978-62365f5cdf5c.png)

* 배열 object 생성
![image](https://user-images.githubusercontent.com/12126093/66712170-a1cd9d00-edd3-11e9-8886-9da094361dca.png)

**qs에서 `plainObjects` 옵션으로 null object를 리턴할 수 있게 한 이유가 뭘까?**
**null object가 필요한 상황은 무엇일까?**

**Comment by tak-bro** [comment]
말그대로 파싱한 데이터의 타입을 primitive인 `null`로 하기 위해 사용하는 듯.
primitive 타입 중 `string`, `number` 같은 타입들은 `Object Prototype`을 갖는데, 내가 알기론 `null`이나 `undefined` 타입만 `prototype`을 가지지 않음.
즉, Object 프로토타입을 갖지 않기 위해 사용한거 아닐까?
`hasOwnProperty`를 예로 든것도 그런 맥락인 듯


![Screen Shot 2019-10-14 at 11 20 59 AM](https://user-images.githubusercontent.com/7614353/66726585-2de3d100-ee75-11e9-83b6-726880f624bc.png)

**Comment by ledgku** [comment]
@tak-bro 

응 자바스크립트의 모든 객체는 [[Prototype]]이라는 인터널 슬롯을 가지고, 그 값은 null 또는 객체여야 한다고 하네.
객체의 [[Prototype]]이 가리키는 링크를 따라서 계속 올라가다 보면 결국 null이 나오는 구조로 되어 있었어.

![image](https://user-images.githubusercontent.com/12126093/66727763-2e339a80-ee7c-11e9-9ea6-6700f46cc0fa.png)

네 말 대로 qs가 생성하는 객체의 속성이 부모 객체의 속성을 override 하지 못하도록 하기 위해 [[Prototype]]이 null 인 객체를 생성할 수 있는 기능이 추가로 있는 것 같아.

자바에서는 이런 문제가 발생하지 않으므로 해당 기능은 없어도 될 것 같아.

**Comment by ledgku** [comment]
test
